server:
  forward-headers-strategy: native
  address: 0.0.0.0
  port: 8888
  ssl:
    enabled: false

spring:
  application:
    name: user-service
  cloud:
    client:
      hostname: 127.0.0.1
      ip-address: 127.0.0.1
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        storage_engine: innodb
        format_sql: false
        use_sql_comments: false
    open-in-view: false
    show_sql: true
  jwt:
    secret: ${JWT_SECRET_KEY}
  web:
    resources:
      add-mappings: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: false

eureka:
  instance:
    instance-id: "${spring.cloud.client.hostname}:${random.int}"
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
